title: FSN Documentation
lang: en
description: FSN Documentation for the FSN FiveM Roleplay Framework

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
